version: "3"

services:
    redis:
        image: redis:latest
        ports: 
            - "6379:6379"
        volumes:
            - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
        command:
            - /usr/local/etc/redis/redis.conf
